FROM alpine:3.8
MAINTAINER "491323832@QQ.com"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add git python3 vim python3-dev && ln -s /usr/bin/python3 /usr/bin/python && git clone https://gitee.com/Vinceeee/myconfig.git /tmp/myconfig && cd /tmp/myconfig && sh init-vim && wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py && python /tmp/get-pip.py && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN mkdir -p /code

# which is used for running this container in deamon mode
VOLUME /code
CMD /usr/sbin/crond -f
