# version: '3'
version: '2'

services:

  master:
    restart: always
    container_name: master
    image: redis:3.2.12-alpine
    ports:
        - 16379:6379
    networks:
      innet:
        ipv4_address: 172.10.10.100

  slaver01:
    container_name: slaver01
    image: redis:3.2.12-alpine
    command: ["--slaveof","master","6379"]
    ports:
        - 16380:6379
    networks:
      innet:
        ipv4_address: 172.10.10.101

  slaver02:
    container_name: slaver02
    image: redis:3.2.12-alpine
    command: ["--slaveof","master","6379"]
    ports:
        - 16381:6379
    networks:
      innet:
        ipv4_address: 172.10.10.102

  sentinel01:
    container_name: sentinel01
    image: redis:3.2.12-alpine
    entrypoint:
        - sh
        - -c
        - "chown -R redis:redis /etc/redis && redis-sentinel /etc/redis/sentinel.conf"
    volumes:
      - ./conf:/etc/redis
    ports:
        - 20000:6379
    networks:
      innet:
        ipv4_address: 172.10.10.103

  sentinel02:
    container_name: sentinel02
    image: redis:3.2.12-alpine
    entrypoint:
        - sh
        - -c
        - "chown -R redis:redis /etc/redis && redis-sentinel /etc/redis/sentinel.conf"
    volumes:
      - ./conf:/etc/redis
    ports:
        - 20001:6379
    networks:
      innet:
        ipv4_address: 172.10.10.105

  sentinel03:
    container_name: sentinel03
    image: redis:3.2.12-alpine
    entrypoint:
        - sh
        - -c
        - "chown -R redis:redis /etc/redis && redis-sentinel /etc/redis/sentinel.conf"
    volumes:
      - ./conf:/etc/redis
    ports:
        - 20002:6379
    networks:
      innet:
        ipv4_address: 172.10.10.106

networks:
  innet:
    ipam:
      driver: default
      config:
      - subnet: 172.10.10.0/24
        gateway: 172.10.10.1

