FROM centos:centos7.5.1804

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

# remove files to enable systemd
ADD ./yum.repos.d/ /etc/yum.repos.d/

RUN yum clean all && \
  yum install -y supervisor vim rsync mariadb mariadb-server python2-PyMySQL \
     rsyslog  && \ 
  yum clean all && rm -rf /var/cache/yum && \
  mkdir -p /var/cache/swift && \
  mkdir -p /var/run/swift && \
  mkdir -p /var/www/swift && \
  systemctl enable rsyncd mariadb

#ENTRYPOINT ["entrypoint.sh"]

CMD ["/usr/sbin/init"]
