version: '2'

# reference : https://github.com/bitnami/bitnami-docker-postgresql

services:
  postgresql-master:
    image: 'bitnami/postgresql:11'
    ports:
      - "5432:5432"
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
#     - './conf:/bitnami/postgresql/conf/'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=abc

volumes:
  postgresql_master_data:
    driver: local
