FROM centos:centos7.5.1804

ADD ./yum.repos.d /etc/yum.repos.d

RUN yum install -y supervisor python-openstackclient openstack-keystone httpd mod_wsgi memcached mod_proxy_uwsgi uwsgi&& \
 yum clean all && rm -rf /var/cache/yum  && mkdir -p /etc/keystone/conf.d  

COPY admin-openrc.sh /opt
COPY keystone.conf /etc/keystone
COPY entrypoint.sh /usr/local/bin
COPY supervisord.conf /etc/supervisord.conf
COPY bin/init_services.sh /usr/local/bin
RUN chmod +x /usr/local/bin/* && ln -s /usr/local/bin/entrypoint.sh /entrypoint.sh # backward compat

# env listed below
# for mariadb 
# ENV DB_CONNECTION mysql+pymysql://keystone:<DB_PASSWD>@<MYSQL_HOST>/keystone
ENV ADMIN_PASS 123456 \
    DB_CONNECTION sqlite:///keystone.db \
    KEYSTONE_BIND_IP 127.0.0.1 \
    MEMCACHED_SERVER 127.0.0.1:11211 \
    SWIFT_ENDPOINT swift:8080

ENTRYPOINT ["entrypoint.sh"]
EXPOSE 5000

CMD supervisord -c /etc/supervisord.conf
