FROM centos:7.5.1804
COPY yum.repo.d /etc/yum.repos.d
RUN yum install -y openstack-dashboard memcache

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
ENV OPENSTACK_HOST 127.0.0.1
ENV MEMCACHED_HOST 127.0.0.1
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 80
CMD ["httpd -DFOREGROUND"]
