#!/usr/bin/env sh

docker run -d --privileged -e OPENSTACK_HOST=192.168.10.106 -e MEMCACHED_HOST=192.168.10.106 --restart=always  --name=horizon --hostname=horizon -v /var/log:/var/log -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8088:80 horizon:latest
