FROM centos:centos7.5.1804

# remove files to enable systemd
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

ADD ./yum.repos.d/ /etc/yum.repos.d/

RUN yum clean all && \
  yum install -y vim gcc gcc-c++ python-devel python2-pip python-swiftclient python-keystoneclient && \
  yum clean all && rm -rf /var/cache/yum && \
  pip install ssbench

CMD ["/usr/sbin/init"]
