FROM centos:centos7.5.1804

# remove files to enable systemd
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

ADD ./yum.repos.d/ /etc/yum.repos.d/

RUN yum clean all && \
  yum install -y vim memcached rsync openstack-swift* python-swiftclient httpd \
     rsyslog xfsprogs xfsdump && \ 
  yum clean all && rm -rf /var/cache/yum && \
  mkdir -p /var/cache/swift && \
  mkdir -p /var/run/swift && \
  systemctl enable memcached rsyncd 

ADD ./config/swift/ /etc/swift/
ADD ./config/rsyncd.conf /etc/rsyncd.conf
ADD ./config/rsyslog.d/ /etc/rsyslog.d/
ADD ./config/test.conf /etc/
ADD ./entrypoint.sh /usr/local/bin
RUN chown -R swift:swift /etc/swift /var/log/swift /var/cache/swift /var/run/swift && chmod +x /usr/local/bin/entrypoint.sh
VOLUME [ "/sys/fs/cgroup","/etc/swift","/var/log" ]
ENV SWIFT_POWER 8
ENV SWIFT_REPLICAS 1
ENTRYPOINT ["entrypoint.sh"]
CMD ["/usr/sbin/init"]
