FROM alpine:3.8
MAINTAINER "491323832@QQ.com"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add python2 python2-dev && wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py && python /tmp/get-pip.py && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && rm -rf /tmp/*
RUN mkdir -p /code

# which is used for running this container in deamon mode
VOLUME /code
CMD /usr/sbin/crond -f
