FROM debian:9
COPY sources.list /etc/apt/sources.list
RUN apt update && apt install vim openjdk-8-jdk rsync ssh -y && rm -rf /var/lib/apt/lists/*
ADD hadoop-2.8.5.tar.gz /opt
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

