FROM centos:centos7.5.1804

# remove files to enable systemd
ADD ./yum.repos.d/ /etc/yum.repos.d/

RUN yum clean all && \
  yum install -y supervisor vim gcc python-devel \
     rsyslog xfsprogs xfsdump python2-pip memcached gettext && \ 
  yum clean all && rm -rf /var/cache/yum && \
  mkdir /horizon

COPY ./horizon /horizon
RUN pip install --no-cache-dir -r /horizon/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ && \
 pip install --no-cache-dir gunicorn python-memcached && \
 cd /horizon && \
 python manage.py compilemessages && \
 python manage.py collectstatic --noinput && \
 python manage.py compress --force 

ADD gunicorn_conf.py /etc
ADD supervisord.conf /etc/supervisord.conf
ADD ./entrypoint.sh /usr/local/bin
RUN ln -s  /horizon/openstack_dashboard/local/local_settings.d local_setting.d

ENV PYTHONPATH=/horizon
ENTRYPOINT ["entrypoint.sh"]

CMD /usr/bin/supervisord -c /etc/supervisord.conf
