FROM centos:centos7.5.1804

ADD ./yum.repos.d/ /etc/yum.repos.d/

RUN  yum makecache && yum install -y supervisor vim memcached rsync openstack-swift* python-swiftclient \
     xfsprogs xfsdump python2-pip && \ 
  pip install keystonemiddleware -i https://pypi.tuna.tsinghua.edu.cn/simple && \
  yum clean all && rm -rf /var/cache/yum && \
  mkdir -p /var/cache/swift && \
  mkdir -p /var/run/swift && \
  mkdir -p /var/log/swift 

ADD supervisord.conf /etc
ADD ./config/swift/ /etc/swift/
ADD ./config/rsyncd.conf /etc/rsyncd.conf
ADD ./config/test.conf /etc/
ADD ./entrypoint.sh /usr/local/bin
RUN chown -R swift:swift  /etc/swift /var/log/swift /var/cache/swift /var/run/swift && chmod +x /usr/local/bin/entrypoint.sh 

ENV SWIFT_POWER 8
ENV SWIFT_REPLICAS 2
ENV SWIFT_LOOP 0
ENV SWIFT_LOOP_SIZE 2G
ENV APACHE_RUN_USER=swift
ENV APACHE_RUN_GROUP=swift
ENTRYPOINT ["entrypoint.sh"]

CMD /usr/bin/supervisord -c /etc/supervisord.conf
#CMD swift-init all start -n 
