FROM centos:7.5.1804
MAINTAINER "491323832@QQ.com"

# set yum and add repo
RUN curl -o /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo && \
    curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
    curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | bash && \
    yum install -y vim gcc gcc-c++ python-devel python-pip sysbench httpd redis && \
    pip install --no-cache-dir pyzmq==14.0.1 --install-option="--zmq=bundled" -i https://mirrors.aliyun.com/pypi/simple/ && \
    pip install --no-cache-dir python-swiftclient ssbench python-keystoneclient -i https://mirrors.aliyun.com/pypi/simple/ && \
    yum remove -y gcc gcc-g++ python-pip && yum clean all && rm -rf /var/cache/yum

CMD ["/usr/sbin/init"] # only for running in daemon
