FROM centos:centos7.5.1804

ADD ./yum.repos.d/ /etc/yum.repos.d/

RUN  yum makecache && yum install -y net-tools supervisor vim memcached rsync openstack-swift* python-swiftclient \
     xfsprogs xfsdump python2-pip && \ 
  pip install keystonemiddleware -i https://pypi.tuna.tsinghua.edu.cn/simple && \
  yum clean all && rm -rf /var/cache/yum && \
  mkdir -p /var/cache/swift && \
  mkdir -p /var/run/swift && \
  mkdir -p /var/log/swift 

ADD supervisord.conf /etc
ADD ./config/swift/ /etc/swift/
ADD ./config/rsyncd.conf /etc/rsyncd.conf
ADD ./config/test.conf /etc/
COPY ./bin /usr/local/bin
ADD ./swift-openrc.sh /opt
RUN chown -R swift:swift  /etc/swift /var/log/swift /var/cache/swift /var/run/swift && chmod +x /usr/local/bin/*

ENV SWIFT_TYPE proxy
ENV RING_DIR /swift_rings
ENV SWIFT_POWER 10
ENV SWIFT_REPLICAS 2
ENV SWIFT_LOOP 1
ENV APACHE_RUN_USER=swift
ENV APACHE_RUN_GROUP=swift
ENV SWIFT_VER=2.15.2
ENTRYPOINT ["entrypoint.sh"]

CMD /usr/bin/supervisord -c /etc/supervisord.conf
