# mariadb version 10.2
#FROM centos:systemd
FROM centos:7.5.1804
ENV MARIADB_MAJOR 10.2
COPY yum.repos.d/ /etc/yum.repos.d/
RUN yum makecache && \
    yum install -y MariaDB-server MariaDB-client && \
    yum clean all && \
    rm -rf /var/cache/yum

COPY start-up.sh /
COPY conf/my.cnf /etc/my.cnf
COPY conf/mysql /etc/mysql
VOLUME /var/lib/mysql
COPY docker-entrypoint.sh /usr/local/bin/
RUN ln -s usr/local/bin/docker-entrypoint.sh / # backwards compat
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 3306

CMD ["/usr/sbin/init"]
