FROM centos:centos7.5.1804

# remove files to enable systemd
ADD ./yum.repos.d/ /etc/yum.repos.d/


# remove basic systemd 
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service  ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum clean all && \
  yum install -y file-devel glib2-devel json-c-devel make autoconf automake openssl openssl-devel libnl3-devel ipset-devel iptables-devel libnfnetlink-devel gcc  libnftnl-devel libmnl-devel && \
  yum clean all && rm -rf /var/cache/yum  && mkdir /opt/keepalived 
  
COPY keepalived /opt/keepalived

# use host cgroup
VOLUME [ "/sys/fs/cgroup"  ]
CMD ["/usr/sbin/init"]
