version: '2'

services:
  app:
    image: gogs/gogs:0.11.79
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./gogs:/data
    restart: always

  drone-server:
    restart: always
    container_name: drone-server
    image: drone/drone:1
    ports:
      - "8888:80"
    volumes:
      - ./drone:/var/lib/drone
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GOGS=true
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_SECRET=c38eb091961962ce7006326f5959a060
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
