# version: '3'
version: '2'

volumes:
    share_data:
    db:

services:
  db:
    container_name: mariadb
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=keystone
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=keystone
    volumes:
        - db:/var/lib/mysql
    networks:
      db:

  keystone:
    container_name: keystone
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    build: ./keystone
    env_file:
      ./keystone/keystone.env
    volumes:
      - share_data:/share
    networks:
      db:
      outnet:

  init_swift_ring:
    container_name: init-swift
    entrypoint: "build_ring.sh"
    build: ./swift
    environment:
      - RING_DIR=/swift-rings
      - REPLICAS=2
      - POWER=10
    volumes:
      - share_data:/share
      - ./bin:/usr/local/bin
      - /tmp/rings:/swift-rings

  proxy:
    container_name: proxy
    restart: always
    depends_on:
      - init_swift_ring
    ports:
      - "8080:8080"
    build: ./swift
    environment:
      - SWIFT_TYPE=proxy
      - RING_DIR=/swift-rings
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings
    networks:
      outnet:
      innet:
        ipv4_address: 172.11.10.100

  storage1:
    container_name: storage1
    restart: always
    build: ./swift
    depends_on:
      - init_swift_ring
    environment:
      - SWIFT_TYPE=storage
      - RING_DIR=/swift-rings
      - SWIFT_DEVICES=swift1,swift2
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings
    networks:
      innet:
        ipv4_address: 172.11.10.1

  storage2:
    container_name: storage2
    restart: always
    build: ./swift
    depends_on:
      - init_swift_ring
    environment:
      - SWIFT_TYPE=storage
      - RING_DIR=/swift-rings
      - SWIFT_DEVICES=swift1,swift2
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings
    networks:
      innet:
        ipv4_address: 172.11.10.2

networks:
  db:
  outnet:
  innet:
    ipam:
      driver: default
      config:
      - subnet: 172.11.10.0/24
        gateway: 172.11.10.10
