version: '3'

volumes:
    share_data:

services:

  init_swift_ring:
    container_name: init-swift
    entrypoint: "build_ring.sh"
    build: ./swift
    environment:
      - RING_DIR=/swift-rings
      - REPLICAS=2
      - POWER=10
    volumes:
      - share_data:/share
      - ./bin:/usr/local/bin
      - /tmp/rings:/swift-rings

  proxy:
    container_name: proxy
    depends_on:
      - init_swift_ring
    ports:
      - "8080:8080"
    build: ./swift
    environment:
      - SWIFT_TYPE=proxy
      - RING_DIR=/swift-rings
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings

  storage1:
    container_name: storage1
    build: ./swift
    depends_on:
      - init_swift_ring
    environment:
      - SWIFT_TYPE=storage
      - RING_DIR=/swift-rings
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings
