version: '3'

volumes:
    share_data:
    db:

services:
  db:
    container_name: mariadb
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=keystone # not supervisor
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=keystone
    volumes:
        - db:/var/lib/mysql

  keystone:
    container_name: keystone
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    build: ./keystone
    environment:
      - KEYSTONE_BIND_IP=192.168.10.10
      - SWIFT_ENDPOINT=192.168.10.10:8080
      - DB_CONNECTION=mysql+pymysql://keystone:123456@db/keystone
    volumes:
      - share_data:/share

  init_swift_ring:
    container_name: init-swift
    entrypoint: "build_ring.sh"
    build: ./swift
    environment:
      - RING_DIR=/swift-rings
      - REPLICAS=2
      - POWER=10
    volumes:
      - share_data:/share
      - ./bin:/usr/local/bin
      - /tmp/rings:/swift-rings

  proxy:
    container_name: proxy
    restart: always
    depends_on:
      - init_swift_ring
    ports:
      - "8080:8080"
    build: ./swift
    environment:
      - SWIFT_TYPE=proxy
      - RING_DIR=/swift-rings
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings

  storage1:
    container_name: storage1
    restart: always
    build: ./swift
    depends_on:
      - init_swift_ring
    environment:
      - SWIFT_TYPE=storage
      - RING_DIR=/swift-rings
      - SWIFT_DEVICES=swift1,swift2
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings

  storage2:
    container_name: storage2
    restart: always
    build: ./swift
    depends_on:
      - init_swift_ring
    environment:
      - SWIFT_TYPE=storage
      - RING_DIR=/swift-rings
      - SWIFT_DEVICES=swift1,swift2
    volumes:
      - share_data:/share
      - /tmp/rings:/swift-rings
