version: '3'

volumes:
    share_data:
    db:

services:
  db:
    container_name: mariadb
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=keystone # not supervisor
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=keystone
    volumes:
        - db:/var/lib/mysql

  keystone:
    container_name: keystone
    depends_on:
      - db
    ports:
      - "5000:5000"
    build: ./keystone
    environment:
      - DB_CONNECTION=mysql+pymysql://keystone:123456@db/keystone
      - KEYSTONE_BIND_IP=192.168.10.10
    volumes:
      - share_data:/share

  swift:
    container_name: swift
    ports:
      - "8080:8080"
    build: ./swift
    environment:
      - SWIFT_LOOP=1
      - SWIFT_REPLICAS=1
    volumes:
      - share_data:/share

