#!/usr/bin/env sh

docker run  -d --privileged -e KEYSTONE_DB_IP=192.168.10.106 --restart=always  --name=keystone1 --hostname=keystone1 -v `pwd`/keystone.conf:/etc/keystone/keystone.conf -v /var/log:/var/log -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 5000:5000  openstack-keystone
