FROM centos:centos7.5.1804

ADD ./yum.repos.d/ /etc/yum.repos.d/
ADD supervisord.conf /etc/supervisord.conf
RUN yum install -y sshpass vim supervisor openssh-server redis openssh-clients python-pip && pip install --no-cache-dir ansible==2.6 -i https://mirrors.aliyun.com/pypi/simple/ && yum clean all 
RUN mkdir /var/run/sshd && /usr/sbin/sshd-keygen -A && touch ~/ansible-hosts

# set password
ENV ROOT_PASSWORD 123456 
# disable host key checking
ENV ANSIBLE_HOST_KEY_CHECKING False
# hostfile
ENV ANSIBLE_INVENTORY ~/ansible-hosts

COPY entrypoint.sh /usr/local/bin
ENTRYPOINT ["entrypoint.sh"]

CMD /usr/bin/supervisord -c /etc/supervisord.conf
